models:
  qwen25vl:
    - name: "Qwen2.5-VL-3B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-3B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256
    - name: "Qwen2.5-VL-7B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-7B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256
    - name: "Qwen2.5-VL-32B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-32B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256
    - name: "Qwen2.5-VL-72B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-72B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256
  
  internvl:
    - name: "InternVL3.5-1B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-1B-Instruct"
      type: "internvl"
    - name: "InternVL3.5-2B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-2B-Instruct"
      type: "internvl"
    - name: "InternVL3.5-4B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-4B-Instruct"
      type: "internvl"
    - name: "InternVL3.5-8B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-8B-Instruct"
      type: "internvl"
    - name: "InternVL3.5-14B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-14B-Instruct"
      type: "internvl"
    - name: "InternVL3.5-30B-A3B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-30B-A3B-Instruct"
      type: "internvl"
    - name: "InternVL3.5-38B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-38B-Instruct"
      type: "internvl"
    - name: "InternVL3.5-241B-A28B-Instruct"
      model_id: "OpenGVLab/InternVL3_5-241B-A28B-Instruct"
      type: "internvl"

inference:
  batch_size: 1
  max_new_tokens: 2048
  temperature: 0.1
  top_p: 0.9
  
device:
  use_multi_gpu: true
  device_map: "auto"
  gpu_memory_utilization: 0.9
  
ocr:
  output_format: "markdown"
  dpi: 300
  image_quality: 95

