models:
  qwen25vl:
    - name: "Qwen2.5-VL-3B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-3B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256
    - name: "Qwen2.5-VL-7B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-7B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256
    - name: "Qwen2.5-VL-32B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-32B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256
    - name: "Qwen2.5-VL-72B-Instruct"
      model_id: "Qwen/Qwen2.5-VL-72B-Instruct"
      type: "qwen25vl"
      max_pixels: 1280
      min_pixels: 256

inference:
  batch_size: 1
  max_new_tokens: 2048
  temperature: 0.1
  top_p: 0.9
  
device:
  use_multi_gpu: true
  device_map: "auto"
  gpu_memory_utilization: 0.9
  
ocr:
  output_format: "markdown"
  dpi: 300
  image_quality: 95

